# SUBCONSULTAS #

/*
-SON CONSULTAS QUE SE EJECUTAN DENTRO DE OTRAS.

-TAMBIEN CONSISTE EN UTILIZAR LOS RESULTADOS DE LA SUBCONSULTA PARA OPERAR EN LA CONSULTA PRINCIPAL.

-ESTO VAMOS A PODER UTILIZARLO GRACIAS A LAS CLAVES FORANEAS / CLAVES AJENAS.
 */

SELECT * FROM users;

